server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: nhan
  datasource:
    url: "jdbc:mysql://localhost:3306/user_system"
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "368ab53ca186843c70301a5c3f75a0f974443d11f6e3d21163268adcdcb7e25a"
  token-duration: 20
  refresh-duration: 120